name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest

    - name: Build Docker Image
      run: |
        docker build -t python-ci-cd:v1 .

    - name: Success Message
      run: echo "Pipeline completed successfully!"

    - name: Check Docker Images
      run: docker images

    - name: Check Docker container
      run: docker run python-ci-cd:v1

    - name: Check Docker container name
      run: docker ps


